name: Greeting

on: push   # Trigger whenever you push

jobs:
  greet:
    runs-on: ubuntu-latest   # The workflow runs inside an Ubuntu VM

    steps:
      - name: Greet User     # Step 1
        run: echo "Hello world"   # Command to execute
